---
- include: postgres.yml
- name: postgres - create mayan database
  sudo_user: "{{ pg_user or ansible_ssh_user }}"
  postgresql_db: >
    name=mayan
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
    login_user="{{ pg_login_user|default(pg_user) }}"
    login_password="{{ pg_login_password|default('')}}"
    login_host="{{ pg_host|default('') }}"
    port="{{ pg_port|default(5432) }}"
  register: mayan_db_create

- name: postgres - create mayan user
  sudo_user: "{{ pg_user or ansible_ssh_user }}"
  postgresql_user: >
    db=mayan
    name=mayan
    password={{ mayan_db_password }}
    login_user="{{ pg_login_user|default(pg_user) }}"
    login_password="{{ pg_login_password|default('')}}"
    login_host="{{ pg_host|default('') }}"
    port="{{ pg_port|default(5432) }}"
  when: mayan_db_create.changed

- name: postgres - apply privileges for mayan user
  sudo_user: "{{ pg_user or ansible_ssh_user }}"
  postgresql_privs: >
    db=mayan
    type=schema
    objs=public
    privs=ALL
    roles=mayan
    login_user="{{ pg_login_user|default(pg_user) }}"
    login_password="{{ pg_login_password|default('')}}"
    login_host="{{ pg_host|default('') }}"
    port="{{ pg_port|default(5432) }}"
  when: mayan_db_create.changed
