---
- name: install postgres client dependencies
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
    force=yes
  with_items:
    - libpq-dev
    - python-psycopg2
  when: localdev is not defined
